#!/usr/bin/env python3
import os
import re
import http.server as h

class Handler(h.SimpleHTTPRequestHandler):
  def guess_type(self, path):
    # default to text/html for all numbered demo pages
    if re.match("^.*\/\d+$", self.path):
      return "text/html; charset=UTF-8"

    return super().guess_type(path)

# change working dir
os.chdir("demo")

# start server
httpd = h.HTTPServer(("localhost", 8000), Handler)
httpd.serve_forever()
