name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        # will assign a random free host port
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        # pg container does not provide a health check
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Postgres
      run: |
        sudo apt install -y libpq-dev
    - name: Install Yarn & Node
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
        sudo apt install -y yarn nodejs
    - name: Build
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get the randomly-assigned port
        RAILS_ENV: test
      run: |
        cp .env.sample .env
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:setup
        yarn install
        bin/rails webpacker:compile
    - name: Test
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }} # get the randomly-assigned port
        RAILS_ENV: test
      run: |
        make t/all
